<?php
require_once("../../config/config.php");

// Only admin access
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../login.php");
    exit;
}

// Set headers for download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=notes_report_' . date('Y-m-d') . '.csv');
header('Pragma: no-cache');
header('Expires: 0');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for UTF-8 (fixes special characters in Excel)
fputs($output, (chr(0xEF) . chr(0xBB) . chr(0xBF)));

// Define escape parameter for PHP 8.1+ compatibility
$escape = "\\";

// ============================================
// Report Header
// ============================================
fputcsv($output, ['NOTES MANAGEMENT REPORT'], ',', '"', $escape);
fputcsv($output, ['Generated Date:', date('F d, Y')], ',', '"', $escape);
fputcsv($output, ['Generated Time:', date('h:i A')], ',', '"', $escape);
fputcsv($output, ['Generated By:', $_SESSION['name'] ?? 'Administrator'], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// ============================================
// Summary Statistics
// ============================================
fputcsv($output, ['SUMMARY STATISTICS'], ',', '"', $escape);
fputcsv($output, ['Total Notes', 'Approved', 'Pending', 'Rejected', 'Total Downloads'], ',', '"', $escape);

// Get statistics
$stats = $pdo->query("
    SELECT 
        COUNT(*) as total,
        SUM(CASE WHEN status = 'approved' THEN 1 ELSE 0 END) as approved,
        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending,
        SUM(CASE WHEN status = 'rejected' THEN 1 ELSE 0 END) as rejected,
        COALESCE(SUM(downloads_count), 0) as downloads
    FROM notes
")->fetch(PDO::FETCH_ASSOC);

fputcsv($output, [
    $stats['total'] ?? 0,
    $stats['approved'] ?? 0,
    $stats['pending'] ?? 0,
    $stats['rejected'] ?? 0,
    $stats['downloads'] ?? 0
], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// ============================================
// Main Data Table
// ============================================
fputcsv($output, ['DETAILED NOTES LIST'], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// Clean headers
$headers = [
    'ID',
    'Title',
    'Category',
    'Type',
    'Status',
    'Downloads',
    'Uploader',
    'Upload Date',
    'File Status'
];
fputcsv($output, $headers, ',', '"', $escape);

// Fetch notes
$notes = $pdo->query("
    SELECT 
        n.id,
        n.title,
        n.type,
        n.status,
        n.downloads_count,
        n.uploaded_at,
        n.file_path,
        u.name AS uploader_name,
        c.name AS category_name
    FROM notes n
    LEFT JOIN users u ON n.user_id = u.id
    LEFT JOIN categories c ON n.category_id = c.id
    ORDER BY n.id ASC
")->fetchAll(PDO::FETCH_ASSOC);

// Add data rows
foreach ($notes as $note) {
    // Clean type name
    $typeName = ucfirst(str_replace('_', ' ', $note['type']));
    if ($note['type'] == 'question_paper') $typeName = 'Past Paper';
    if ($note['type'] == 'assessment') $typeName = 'Assessment';
    if ($note['type'] == 'note') $typeName = 'Note';
    
    // Clean status
    $statusName = ucfirst($note['status']);
    
    // Check if file exists
    $fileCheck = 'Available';
    $filePath = "../../uploads/" . basename($note['file_path']);
    if (!file_exists($filePath)) {
        $fileCheck = 'Missing';
    }
    
    fputcsv($output, [
        $note['id'],
        $note['title'],
        $note['category_name'] ?? 'Uncategorized',
        $typeName,
        $statusName,
        (int)$note['downloads_count'],
        $note['uploader_name'] ?? 'Unknown',
        date('Y-m-d', strtotime($note['uploaded_at'])),
        $fileCheck
    ], ',', '"', $escape);
}

// ============================================
// Category Summary
// ============================================
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, ['CATEGORY SUMMARY'], ',', '"', $escape);
fputcsv($output, ['Category', 'Total Notes', 'Total Downloads'], ',', '"', $escape);

$categories = $pdo->query("
    SELECT 
        c.name,
        COUNT(n.id) as note_count,
        COALESCE(SUM(n.downloads_count), 0) as total_downloads
    FROM categories c
    LEFT JOIN notes n ON c.id = n.category_id
    GROUP BY c.id
    ORDER BY note_count DESC
")->fetchAll(PDO::FETCH_ASSOC);

foreach ($categories as $cat) {
    fputcsv($output, [
        $cat['name'],
        $cat['note_count'],
        $cat['total_downloads']
    ], ',', '"', $escape);
}

// ============================================
// User Summary
// ============================================
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, ['TOP CONTRIBUTORS'], ',', '"', $escape);
fputcsv($output, ['User', 'Role', 'Uploads', 'Downloads Generated'], ',', '"', $escape);

$users = $pdo->query("
    SELECT 
        u.name,
        u.role,
        COUNT(n.id) as upload_count,
        COALESCE(SUM(n.downloads_count), 0) as downloads_generated
    FROM users u
    LEFT JOIN notes n ON u.id = n.user_id
    GROUP BY u.id
    ORDER BY upload_count DESC
    LIMIT 10
")->fetchAll(PDO::FETCH_ASSOC);

foreach ($users as $user) {
    fputcsv($output, [
        $user['name'],
        ucfirst($user['role']),
        $user['upload_count'],
        $user['downloads_generated']
    ], ',', '"', $escape);
}

// ============================================
// Footer
// ============================================
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, ['End of Report'], ',', '"', $escape);
fputcsv($output, ['Total Records:', count($notes)], ',', '"', $escape);

fclose($output);
exit;
?>