<?php
require_once("../../config/config.php");

// Only admin access
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../login.php");
    exit;
}

// Set headers for download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=categories_report_' . date('Y-m-d') . '.csv');
header('Pragma: no-cache');
header('Expires: 0');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for UTF-8
fputs($output, (chr(0xEF) . chr(0xBB) . chr(0xBF)));

// Define escape parameter for PHP 8.1+ compatibility
$escape = "\\";

// ============================================
// Report Header
// ============================================
fputcsv($output, ['CATEGORIES REPORT'], ',', '"', $escape);
fputcsv($output, ['Generated Date:', date('F d, Y')], ',', '"', $escape);
fputcsv($output, ['Generated Time:', date('h:i A')], ',', '"', $escape);
fputcsv($output, ['Generated By:', $_SESSION['name'] ?? 'Administrator'], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// ============================================
// Summary
// ============================================
$totalCategories = $pdo->query("SELECT COUNT(*) FROM categories")->fetchColumn();
$totalNotesInCategories = $pdo->query("
    SELECT COUNT(*) FROM notes WHERE category_id IS NOT NULL
")->fetchColumn();

fputcsv($output, ['SUMMARY'], ',', '"', $escape);
fputcsv($output, ['Total Categories', $totalCategories], ',', '"', $escape);
fputcsv($output, ['Notes Categorized', $totalNotesInCategories], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// ============================================
// Main Data Table
// ============================================
fputcsv($output, ['CATEGORIES DETAILS'], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

$headers = [
    'ID',
    'Category Name',
    'Total Notes',
    'Total Downloads'
];
fputcsv($output, $headers, ',', '"', $escape);

$categories = $pdo->query("
    SELECT 
        c.id,
        c.name,
        COUNT(n.id) as total_notes,
        COALESCE(SUM(n.downloads_count), 0) as total_downloads
    FROM categories c
    LEFT JOIN notes n ON c.id = n.category_id
    GROUP BY c.id
    ORDER BY total_notes DESC
")->fetchAll(PDO::FETCH_ASSOC);

foreach ($categories as $category) {
    fputcsv($output, [
        $category['id'],
        $category['name'],
        (int)$category['total_notes'],
        (int)$category['total_downloads']
    ], ',', '"', $escape);
}

// ============================================
// Footer
// ============================================
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, ['End of Report'], ',', '"', $escape);
fputcsv($output, ['Total Categories:', count($categories)], ',', '"', $escape);

fclose($output);
exit;
?>