<?php
require_once("../../config/config.php");

// Only admin access
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../login.php");
    exit;
}

// Set headers for download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=users_report_' . date('Y-m-d') . '.csv');
header('Pragma: no-cache');
header('Expires: 0');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for UTF-8
fputs($output, (chr(0xEF) . chr(0xBB) . chr(0xBF)));

// Define escape parameter for PHP 8.1+ compatibility
$escape = "\\";

// ============================================
// Report Header
// ============================================
fputcsv($output, ['USERS MANAGEMENT REPORT'], ',', '"', $escape);
fputcsv($output, ['Generated Date:', date('F d, Y')], ',', '"', $escape);
fputcsv($output, ['Generated Time:', date('h:i A')], ',', '"', $escape);
fputcsv($output, ['Generated By:', $_SESSION['name'] ?? 'Administrator'], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// ============================================
// Summary Statistics
// ============================================
fputcsv($output, ['SUMMARY STATISTICS'], ',', '"', $escape);
fputcsv($output, ['Total Users', 'Students', 'Teachers', 'Admins'], ',', '"', $escape);

$userStats = $pdo->query("
    SELECT 
        COUNT(*) as total,
        SUM(CASE WHEN role = 'student' THEN 1 ELSE 0 END) as students,
        SUM(CASE WHEN role = 'teacher' THEN 1 ELSE 0 END) as teachers,
        SUM(CASE WHEN role = 'admin' THEN 1 ELSE 0 END) as admins
    FROM users
")->fetch(PDO::FETCH_ASSOC);

fputcsv($output, [
    $userStats['total'] ?? 0,
    $userStats['students'] ?? 0,
    $userStats['teachers'] ?? 0,
    $userStats['admins'] ?? 0
], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// ============================================
// Main Data Table
// ============================================
fputcsv($output, ['DETAILED USERS LIST'], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);

// Clean headers
$headers = [
    'ID',
    'Name',
    'Email',
    'Role',
    'Profile Picture',
    'Uploads',
    'Downloads Generated',
    'Joined Date'
];
fputcsv($output, $headers, ',', '"', $escape);

// Fetch users with stats
$users = $pdo->query("
    SELECT 
        u.id,
        u.name,
        u.email,
        u.role,
        u.profile_picture,
        u.created_at,
        COUNT(DISTINCT n.id) as total_uploads,
        COALESCE(SUM(n.downloads_count), 0) as downloads_generated
    FROM users u
    LEFT JOIN notes n ON u.id = n.user_id
    GROUP BY u.id
    ORDER BY u.id ASC
")->fetchAll(PDO::FETCH_ASSOC);

foreach ($users as $user) {
    fputcsv($output, [
        $user['id'],
        $user['name'],
        $user['email'],
        ucfirst($user['role']),
        $user['profile_picture'] ? 'Yes' : 'No',
        (int)$user['total_uploads'],
        (int)$user['downloads_generated'],
        date('Y-m-d', strtotime($user['created_at']))
    ], ',', '"', $escape);
}

// ============================================
// Footer
// ============================================
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, [], ',', '"', $escape);
fputcsv($output, ['End of Report'], ',', '"', $escape);
fputcsv($output, ['Total Records:', count($users)], ',', '"', $escape);

fclose($output);
exit;
?>